mysql:
  enable: true
  host: localhost
  database: mc_mycraft
  tablename: 'QA_playerdata'
  username: mclogblock
  password: 'ZGfXLH7qRSuDMpqe'
  port: 3306

QA:
  1:
    question: 问题1
    answer: 回答1
    reward: 1
    firstreward: 1
  2:
    question: 问题2
    answer: 回答2
    reward: 2
    firstreward: 2
  3:
    question: 问题2
    answer: 回答2
    reward: 2
    firstreward: 2
  4:
    question: 问题2
    answer: 回答2
    reward: 2
    firstreward: 2
  5:
    question: 问题2
    answer: 回答2
    reward: 2
    firstreward: 2

reward:
  1:
    cmd: 'give @a minecraft:diamond_sword 1 0 {Unbreakable:1}'
  2:
    cmd: 'give @a minecraft:diamond_sword 1 0 {Unbreakable:1}'

firstreward:
  1:
    cmd: 'give @a minecraft:diamond_sword 1 0 {Unbreakable:1}'
  2:
    cmd: 'give @a minecraft:diamond_sword 1 0 {Unbreakable:1}'